title: "OaKhz EQ"
description: "EQ 10 bandes basé sur Alsaequal - mêmes réglages pour L et R"

devices:
  samplerate: 44100  # ou 48000 selon ta source
  chunksize: 1024
  capture:
    type: Stdin
    channels: 2
    format: S32LE
  playback:
    type: Alsa
    channels: 2
    device: plughw:0,0
    format: S32LE

filters:
  EQ1:
    type: Biquad
    parameters: { type: Peaking, freq: 31, q: 1.0, gain: 2 }
  EQ2:
    type: Biquad
    parameters: { type: Peaking, freq: 63, q: 1.0, gain: 3 }
  EQ3:
    type: Biquad
    parameters: { type: Peaking, freq: 125, q: 1.0, gain: 3 }
  EQ4:
    type: Biquad
    parameters: { type: Peaking, freq: 250, q: 1.0, gain: 0 }
  EQ5:
    type: Biquad
    parameters: { type: Peaking, freq: 500, q: 1.0, gain: -3 }
  EQ6:
    type: Biquad
    parameters: { type: Peaking, freq: 1000, q: 1.0, gain: -5 }
  EQ7:
    type: Biquad
    parameters: { type: Peaking, freq: 2000, q: 1.0, gain: -5 }
  EQ8:
    type: Biquad
    parameters: { type: Peaking, freq: 4000, q: 1.0, gain: -3 }
  EQ9:
    type: Biquad
    parameters: { type: Peaking, freq: 8000, q: 1.0, gain: 0 }
  EQ10:
    type: Biquad
    parameters: { type: Peaking, freq: 16000, q: 1.0, gain: 0 }

pipeline:
  - type: Filter
    names: [EQ1, EQ2, EQ3, EQ4, EQ5, EQ6, EQ7, EQ8, EQ9, EQ10]
    channels: [0, 1]
